version: '3.7'

networks:
  docker-eth:
    name: docker-eth
    driver: bridge

services:
  mysql_db:
    hostname: mysql_db
    container_name: mysql_db
    image: mysql
    networks:
      - docker-eth
    restart: unless-stopped
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password --init-file /data/init.sql
    volumes:
        - ./src/main/resources/init.sql:/data/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 111222333
  bid_app:
    hostname: bid_app
    container_name: bid_app
    build:
      context: .
      dockerfile: Dockerfile
    image: bid_app
    networks:
      - docker-eth
    restart: unless-stopped
    ports:
      - 8080:8080
